{% set version = "0.16.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ranger
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ranger_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ranger/ranger_{{ version }}.tar.gz
  sha256: 0395f93afdb807a7882c1fa8f183a26a871c5168ea0903566951298ef1138589
  patches:
    - patches/0001_cxx14_win.patch

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-rcpp >=0.11.2
    - r-rcppeigen
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-matrix
    - r-rcpp >=0.11.2
    - r-rcppeigen

test:
  commands:
    - $R -e "library('ranger')"           # [not win]
    - "\"%R%\" -e \"library('ranger')\""  # [win]

about:
  home: https://github.com/imbs-hl/ranger
  license: GPL-3.0-only
  summary: A fast implementation of Random Forests, particularly suited for high dimensional data. Ensembles of classification, regression, survival and probability prediction trees are supported. Data from genome-wide association studies can be analyzed efficiently. In addition to data frames, datasets of class 'gwaa.data'
    (R package 'GenABEL') and 'dgCMatrix' (R package 'Matrix')  can be directly analyzed.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - rvalieris
