{% set version = "0.18.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ranger
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ranger_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ranger/ranger_{{ version }}.tar.gz
  sha256: 94c5e4c67cd92292bbba72e71d1a89be6ddea1a0d7b8e7ad452e0609b675b44d
  patches:
    - patches/0001_cxx14_win.patch

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - r-matrix                   # [build_platform != target_platform]
    - r-rcppeigen                # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-rcpp >=0.11.2
    - r-rcppeigen
  run:
    - r-base
    - r-matrix
    - r-rcpp >=0.11.2
    - r-rcppeigen

test:
  commands:
    - $R -e "library('ranger')"           # [not win]
    - "\"%R%\" -e \"library('ranger')\""  # [win]

about:
  home: https://github.com/imbs-hl/ranger
  license: GPL-3.0-only
  summary: A fast implementation of Random Forests, particularly suited for high dimensional data. Ensembles of classification, regression, survival and probability prediction trees are supported. Data from genome-wide association studies can be analyzed efficiently. In addition to data frames, datasets of class 'gwaa.data'
    (R package 'GenABEL') and 'dgCMatrix' (R package 'Matrix')  can be directly analyzed.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - rvalieris
