{% set version = "0.12.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ranger
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ranger_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ranger/ranger_{{ version }}.tar.gz
  sha256: da48fbbffc533d9038fae491ef8fbd50f64c38d219ccc4e77b2d8919fda17831

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-rcpp >=0.11.2
    - r-rcppeigen
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix
    - r-rcpp >=0.11.2
    - r-rcppeigen

test:
  commands:
    - $R -e "library('ranger')"           # [not win]
    - "\"%R%\" -e \"library('ranger')\""  # [win]

about:
  home: https://github.com/imbs-hl/ranger
  license: GPL-3
  summary: A fast implementation of Random Forests, particularly suited for high dimensional
    data. Ensembles of classification, regression, survival and probability prediction
    trees are supported. Data from genome-wide association studies can be analyzed efficiently.
    In addition to data frames, datasets of class 'gwaa.data' (R package 'GenABEL')
    and 'dgCMatrix' (R package 'Matrix')  can be directly analyzed.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - rvalieris

# Package: ranger
# Type: Package
# Title: A Fast Implementation of Random Forests
# Version: 0.11.2
# Date: 2019-03-07
# Author: Marvin N. Wright [aut, cre], Stefan Wager [ctb], Philipp Probst [ctb]
# Maintainer: Marvin N. Wright <cran@wrig.de>
# Description: A fast implementation of Random Forests, particularly suited for high dimensional data. Ensembles of classification, regression, survival and probability prediction trees are supported. Data from genome-wide association studies can be analyzed efficiently. In addition to data frames, datasets of class 'gwaa.data' (R package 'GenABEL') and 'dgCMatrix' (R package 'Matrix')  can be directly analyzed.
# License: GPL-3
# Imports: Rcpp (>= 0.11.2), Matrix
# LinkingTo: Rcpp, RcppEigen
# Depends: R (>= 3.1)
# Suggests: survival, testthat
# RoxygenNote: 6.1.1
# URL: https://github.com/imbs-hl/ranger
# BugReports: https://github.com/imbs-hl/ranger/issues
# NeedsCompilation: yes
# Packaged: 2019-03-07 12:01:18 UTC; wright
# Repository: CRAN
# Date/Publication: 2019-03-07 14:10:20 UTC
