{% set version = "0.11.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ranger
  version: {{ version|replace("-", "_") }}

source:
  fn: ranger_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ranger_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ranger/ranger_{{ version }}.tar.gz
  sha256: 999fb114602e27601ff0fe8ab461c39d667c6f5e8434e7feb3d21c7caf0dcffb

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-rcpp >=0.11.2
    - r-rcppeigen
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix
    - r-rcpp >=0.11.2
    - r-rcppeigen

test:
  commands:
    - $R -e "library('ranger')"           # [not win]
    - "\"%R%\" -e \"library('ranger')\""  # [win]

about:
  home: https://github.com/imbs-hl/ranger
  license: GPL-3
  summary: A fast implementation of Random Forests, particularly suited for high dimensional
    data. Ensembles of classification, regression, survival and probability prediction
    trees are supported. Data from genome-wide association studies can be analyzed efficiently.
    In addition to data frames, datasets of class 'gwaa.data' (R package 'GenABEL')
    and 'dgCMatrix' (R package 'Matrix')  can be directly analyzed.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - rvalieris
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
