# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DB5RMCQk0LHBcdWC3Watz/Fpa2zvLWmmXG2khX7pSdEboyiU+/rLBp7d6hlhwmpf7pbFoSFzkHt07dHGXqa2MqstRB83NEECjW7V2UyfMJPKjMWcMg2igmcEsu4Rmu7U9zx6oeJatxOzKdgjpnPccTd9A1Guq1fn5PWfxLE2AHqGvsNvOa6ymcWIvfLuqrsKFM9Jf83+Xo2l5tfse7iSXH/MoR988xKDfSsydbXXSmfhjV42crfWgwsOP8HbNPC9S01wczC+pggHT2zuhzxXHFLWwwC0kZatnSHJ//3vINcV4Fcp/1COyd9UCRaDnRQjNxnl/awj1o40kLD8rtkFfP4mSmh4ZYfQJ9Cg1ElyQdp5pY6MVVHAp6Ri+PBds5RJVr7OmVXW7FhZiUugJE/7ZbMuir0H3fqxe/qatJTnNgS7vn54DtOiA0oo//v48HFuS0N4U4XcbV/uGjnzBMrUDr9q8okSHXZAT0ceI/Mig5zXvO+m4A3moGJKuri3JSM3WWW1Z4RCFg9bp4Q1+v+1/VGF81SDqt+wMjeMveO8hctnSVvEzYFV7SA1NduV78L4Tz3PihmWd7qA2gTxJ1eJwtpf1oNslpzSnfryBALGeZzGJPgjYbIGwKzpjCswH985z0U3+F075FPyMoNI6RClcHsuRQaKotlbggdM+4dGfCY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
