appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: DB5RMCQk0LHBcdWC3Watz/Fpa2zvLWmmXG2khX7pSdEboyiU+/rLBp7d6hlhwmpf7pbFoSFzkHt07dHGXqa2MqstRB83NEECjW7V2UyfMJPKjMWcMg2igmcEsu4Rmu7U9zx6oeJatxOzKdgjpnPccTd9A1Guq1fn5PWfxLE2AHqGvsNvOa6ymcWIvfLuqrsKFM9Jf83+Xo2l5tfse7iSXH/MoR988xKDfSsydbXXSmfhjV42crfWgwsOP8HbNPC9S01wczC+pggHT2zuhzxXHFLWwwC0kZatnSHJ//3vINcV4Fcp/1COyd9UCRaDnRQjNxnl/awj1o40kLD8rtkFfP4mSmh4ZYfQJ9Cg1ElyQdp5pY6MVVHAp6Ri+PBds5RJVr7OmVXW7FhZiUugJE/7ZbMuir0H3fqxe/qatJTnNgS7vn54DtOiA0oo//v48HFuS0N4U4XcbV/uGjnzBMrUDr9q8okSHXZAT0ceI/Mig5zXvO+m4A3moGJKuri3JSM3WWW1Z4RCFg9bp4Q1+v+1/VGF81SDqt+wMjeMveO8hctnSVvEzYFV7SA1NduV78L4Tz3PihmWd7qA2gTxJ1eJwtpf1oNslpzSnfryBALGeZzGJPgjYbIGwKzpjCswH985z0U3+F075FPyMoNI6RClcHsuRQaKotlbggdM+4dGfCY=}
